drop policy "Enable read access for all users" on "public"."testimonials";

create table "public"."skills" (
    "id" bigint generated by default as identity not null,
    "level" text not null,
    "type" text not null,
    "sub_type" text,
    "name" text not null
);


alter table "public"."skills" enable row level security;

alter table "public"."testimonials" alter column "company" set not null;

alter table "public"."testimonials" alter column "company_logo_url" set not null;

alter table "public"."testimonials" alter column "description" set not null;

alter table "public"."testimonials" alter column "email" set not null;

alter table "public"."testimonials" alter column "quote" set not null;

CREATE UNIQUE INDEX skills_name_key ON public.skills USING btree (name);

CREATE UNIQUE INDEX skills_pkey ON public.skills USING btree (id);

alter table "public"."skills" add constraint "skills_pkey" PRIMARY KEY using index "skills_pkey";

alter table "public"."skills" add constraint "skills_name_key" UNIQUE using index "skills_name_key";

create policy "Enable read access for all users"
on "public"."skills"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."testimonials"
as permissive
for select
to public
using (true);



